syntax = "proto3";

package if97;

service WaterProperties {
  // Расчет по давлению (MPa) и температуре (K)
  rpc CalculatePT (PointPT) returns (WaterStateResponse);

  // Расчет по давлению (MPa) и энтальпии (kJ/kg)
  rpc CalculatePH (PointPH) returns (WaterStateResponse);

  // Расчет по давлению (MPa) и энтропии (kJ/(kg*K))
  rpc CalculatePS (PointPS) returns (WaterStateResponse);

  // Расчет на линии насыщения (двухфазная область)
  rpc CalculateTwoPhase (PointPX) returns (WaterStateResponse);
}

message PointPT {
  double p = 1; // Давление, МПа
  double t = 2; // Температура, K
}

message PointPH {
  double p = 1;
  double h = 2; // Энтальпия
}

message PointPS {
  double p = 1;
  double s = 2; // Энтропия
}

message PointPX {
  double p = 1;
  double x = 2; // Степень сухости [0.0 - 1.0]
}

message WaterStateResponse {
  double p = 1;
  double t = 2;
  double v = 3;
  double rho = 4;
  double h = 5;
  double s = 6;
  double cp = 7;
  double w = 8;
  int32 region = 9; // Номер региона (1-5)
}