[package]
name = "grpc_server"
version = "0.1.0"
edition = "2024"

[dependencies]
if97_core = { path = "../core" } # Подключаем наше локальное ядро
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[build-dependencies]
tonic-build = "0.12"