use std::env;
use std::fs;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Указываем Cargo пересобирать проект только если изменилось содержимое папки data/
    println!("cargo:rerun-if-changed=data/");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR не задан");
    let dest_path = Path::new(&out_dir).join("tables.rs");
    let data_dir = Path::new("data");

    let mut generated_code = String::new();
    generated_code.push_str("// AUTO-GENERATED BY build.rs\n");
    generated_code.push_str("// IAPWS-IF97 coefficients from CSV files\n");
    generated_code.push_str("// DO NOT EDIT MANUALLY\n\n");

    if let Ok(entries) = fs::read_dir(data_dir) {
        let mut paths: Vec<_> = entries
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|ext| ext == "csv"))
            .collect();

        // Сортируем пути для детерминированности сборки
        paths.sort();

        for path in paths {
            let file_stem = path.file_stem().unwrap().to_str().unwrap().to_uppercase();
            let contents = fs::read_to_string(&path).expect("Не удалось прочитать CSV файл");

            // Собираем валидные строки, разбитые на колонки
            let mut valid_lines = Vec::new();
            for line in contents.lines() {
                let line = line.trim();
                if line.is_empty() { continue; }
                let parts: Vec<&str> = line.split(',').map(|s| s.trim()).collect();
                valid_lines.push(parts);
            }

            if valid_lines.is_empty() { continue; }
            let cols = valid_lines[0].len();

            // Динамически определяем типы колонок (начиная со 2-й)
            // 1-я колонка всегда f64 (коэффициент n)
            let mut col_types = vec!["f64".to_string()];
            for col_idx in 1..cols {
                let mut is_float = false;
                for parts in &valid_lines {
                    if parts.len() > col_idx {
                        let val_str = parts[col_idx];
                        // Если строка не парсится как строгое целое i32 (например, есть точка), значит это f64
                        if val_str.parse::<i32>().is_err() {
                            is_float = true;
                            break;
                        }
                    }
                }
                col_types.push(if is_float { "f64".to_string() } else { "i32".to_string() });
            }

            // Формируем сигнатуру типа массива (поддерживаем до 4 колонок для Региона 3)
            let type_decl = match cols {
                1 => "f64".to_string(),
                2 => format!("(f64, {})", col_types[1]),
                3 => format!("(f64, {}, {})", col_types[1], col_types[2]),
                4 => format!("(f64, {}, {}, {})", col_types[1], col_types[2], col_types[3]),
                _ => panic!("Неподдерживаемое количество колонок ({}) в файле {:?}", cols, path),
            };

            generated_code.push_str(&format!("pub const {}: &[{}] = &[\n", file_stem, type_decl));

            // Генерируем данные с учетом определенных типов
            for (line_num, parts) in valid_lines.iter().enumerate() {
                if cols == 1 {
                    let n: f64 = parts[0].parse().unwrap_or_else(|_| panic!("Ошибка n в {:?}:{}", path, line_num));
                    generated_code.push_str(&format!("    {:16e},\n", n));
                } else {
                    generated_code.push_str("    (");
                    let n: f64 = parts[0].parse().unwrap_or_else(|_| panic!("Ошибка n в {:?}:{}", path, line_num));
                    generated_code.push_str(&format!("{:16e}", n));

                    for col_idx in 1..cols {
                        if col_types[col_idx] == "f64" {
                            let val: f64 = parts[col_idx].parse().unwrap_or_else(|_| panic!("Ошибка f64 в {:?}:{} (col {})", path, line_num, col_idx));
                            generated_code.push_str(&format!(", {:16e}", val));
                        } else {
                            let val: i32 = parts[col_idx].parse().unwrap_or_else(|_| panic!("Ошибка i32 в {:?}:{} (col {})", path, line_num, col_idx));
                            generated_code.push_str(&format!(", {}", val));
                        }
                    }
                    generated_code.push_str("),\n");
                }
            }
            generated_code.push_str("];\n\n");
        }
    } else {
        println!("cargo:warning=Директория 'data' не найдена. Таблицы не будут сгенерированы.");
    }

    fs::write(&dest_path, generated_code).expect("Не удалось записать сгенерированный файл tables.rs");
    Ok(())
}